### ISSUE TITLE
Broken GitHub Repo Section

### ISSUE THREAD

**Issue by Grafaffel** [JanjyTapYT/portfolio#7]
# **Broken GitHub Repo Section**

## Steps to reproduce
1. Go to https://nilsdev.linkgames.de/projects
2. Scroll to the Repositories Section
3. Click on the Linkcord Repository
4. Observe

# Expected Result
File tree of the repository

# Actual Result
The whole page gets blurred

# Additional Info
| Browser     | Chrome 127.0.6533.88 |
| ----------- | -------------------- |
| Screen Size | 1920 x 1080          |
| OS          | Windows 10           |

> [!NOTE]
> If you look at the Network tab in the Inspector, the request to retrieve the files is successful.

---

### Attachments
![result](https://github.com/user-attachments/assets/6f7fa99c-4f39-4df8-8adf-ffed0b8c4ee4)

**Comment by nilscrafthd** [comment]
@binary-blazer

**Comment by builtbyjonas** [comment]
That's a sorting problem by ``framer-motion`` so I cannot really do anything about it but try to work on a workaround. I will investigate this issue! @Grafaffel @Nils-afk

**Comment by builtbyjonas** [comment]
@Grafaffel I finally got some time to fix it. The issue is resolved. However, I cannot apply the update to the site from "NilsDev". He has to do it himself.

https://github.com/binary-blazer/portfolio/releases/tag/v3.6.0
